config/routes.rb
Rails.application.routes.draw do
  root to: "suppliers#index"

  resources :suppliers do 
    collection do
      get :search 
    end
  end    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    validates :suppliername, :presence => true
    validates :gstno, :presence => true
    validates :dlno20b, :presence => true
    validates :dlno21b, :presence => true

    def self.search(params)
        suppliers = Supplier.where("suppliername ILIKE ?", "%#{params[:search]}%") if params[:search].present?
        return suppliers
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  def search 
    if params[:search].blank?
      @suppliers = Supplier.all.paginate(page: params[:page], per_page: 10)
    else
      @suppliers = Supplier.search(params)
    end
  end  

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: 'Supplier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supplier_params
      params.require(:supplier).permit(:suppliername, :primarycontact, :address, :contactno, :email, :gstno, :dlno20b, :dlno21b)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventoryProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/suppliers/_form.html.erb
<%= form_with(model: supplier, local: true) do |form| %>
  <% if supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
        <% supplier.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :suppliername, "Supplier Name" %>
    <%= form.text_field :suppliername, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :primarycontact, "Primary Contact" %>
    <%= form.text_field :primarycontact, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address, "Address" %>
    <%= form.text_area :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :contactno, "Contact Number" %>
    <%= form.text_field :contactno, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email, "Email" %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :gstno, "GST NO" %>
    <%= form.text_field :gstno, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :dlno20b, "DLNO20B" %>
    <%= form.text_field :dlno20b, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :dlno21b, "DLNO21B" %>
    <%= form.text_field :dlno21b, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'save supplier', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<div class="container" style="margin-top: 30px">
 <div class="card">
  <div class="card-header bg-info"><h2>Edit Supplier Record</h2></div>
    <div class="card-body">

            <%= render 'form', supplier: @supplier %>

        <div class="row">
          <div class="col-md-6">
            <%= link_to 'Show', @supplier , class: 'btn btn-warning btn-block'%> 
          </div>
          <div class="col-md-6">
            <%= link_to 'Back', suppliers_path, class: 'btn btn-danger btn-block'%>
          </div>
        </div>    

    </div>
 </div>
</div>            

app/views/suppliers/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align:center">Suppliers</h1>

<br>

    <%= link_to 'ADD NEW SUPPLIER', new_supplier_path, class: 'btn btn-mini btn-success' %> 

<hr>

    <%= form_tag(search_suppliers_path, :method => "get",   
        class: 'navbar-form navbar-left') do %>  
      <div class="input-group">  
        <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>   
      </div>  
    <% end %> 

<div class="table-wrapper">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Supplier Name</th>
      <th>Primary Contact</th>
      <th>Address</th>
      <th>ContactNo</th>
      <th>Email</th>
      <th>GSTNO</th>
      <th>DLNO20B</th>
      <th>DLNO21B</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.suppliername %></td>
        <td><%= supplier.primarycontact %></td>
        <td><%= supplier.address %></td>
        <td><%= supplier.contactno %></td>
        <td><%= supplier.email %></td>
        <td><%= supplier.gstno %></td>
        <td><%= supplier.dlno20b %></td>
        <td><%= supplier.dlno21b %></td>
        <td><%= link_to 'Show', supplier, class: 'btn btn-mini btn-info' %></td>
        <td><%= link_to 'Edit', edit_supplier_path(supplier), class: 'btn btn-mini btn-warning' %></td>
        <td><%= link_to 'Destroy', supplier, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= will_paginate @suppliers, renderer: BootstrapPagination::Rails  %>

app/views/suppliers/new.html.erb
<div class="container" style="margin-top: 30px">
 <div class="card">
  <div class="card-header bg-warning"><h2>New Supplier</h2></div>
    <div class="card-body">

        <%= render 'form', supplier: @supplier %>

        <%= link_to 'Back', suppliers_path, class: "btn btn-danger btn-block" %>
     
    </div>
   </div> 
  </div>
</div>

app/views/suppliers/search.html.erb
<p id="notice"><%= notice %></p>

<h2 style="text-align:center">Search Results </h2>

<div class="media">
  <div class="media-body">
    <div class="table-wrapper">
        <table class="table table-striped table-hover">
        <thead>
            <tr>
            <th>Supplier Name</th>
            <th>Primary Contact</th>
            <th>Address</th>
            <th>ContactNo</th>
            <th>Email</th>
            <th>GSTNO</th>
            <th>DLNO20B</th>
            <th>DLNO21B</th>
            <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @suppliers.each do |supplier| %>
            <tr>
                <td><%= supplier.suppliername %></td>
                <td><%= supplier.primarycontact %></td>
                <td><%= supplier.address %></td>
                <td><%= supplier.contactno %></td>
                <td><%= supplier.email %></td>
                <td><%= supplier.gstno %></td>
                <td><%= supplier.dlno20b %></td>
                <td><%= supplier.dlno21b %></td>
                <td><%= link_to 'Show', supplier, class: 'btn btn-mini btn-info' %></td>
                <td><%= link_to 'Edit', edit_supplier_path(supplier), class: 'btn btn-mini btn-warning' %></td>
                <td><%= link_to 'Destroy', supplier, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </tbody>
        </table>
    </div>
  </div>
</div>  

<p>
  <%= link_to 'Back to all master data', suppliers_path, class: 'btn btn-mini btn-warning' %>
</p>

app/views/suppliers/show.html.erb
<div class="container" style="margin-top: 30px">
 <div class="card">
  <div class="card-header bg-success"><h2>Supplier details</h2></div>
   <div class="card-body">
    <p id="notice"><%= notice %></p>

    <div class="form-group row">
        <div class="col-sm-3 col-form-label"><h5>Supplier Name:</h5></div>
        <div class="col-sm-9"><h5><%= @supplier.suppliername %></h5></div>
    </div>

    <div class="form-group row">
        <div class="col-sm-3 col-form-label"><h5>Primary Contact:</h5></div>
        <div class="col-sm-9"><h5><%= @supplier.primarycontact %></h5></div>
    </div>

    <div class="form-group row">
        <div class="col-sm-3 col-form-label"><h5>Address:</h5></div>
        <div class="col-sm-9"><h5><%= @supplier.address %></h5></div>
    </div>

    <div class="form-group row">
    <div class="col-sm-3 col-form-label"><h5>ContactNo:</h5></div>
    <div class="col-sm-9"><h5><%= @supplier.contactno %></h5></div>
    </div>

    <div class="form-group row">
    <div class="col-sm-3 col-form-label"><h5>Email:</h5></div>
    <div class="col-sm-9"><h5><%= @supplier.email %></h5></div>
    </div>

    <div class="form-group row">
        <div class="col-sm-3 col-form-label"><h5>GSTNO:</h5></div>
        <div class="col-sm-9"><h5><%= @supplier.gstno %></h5></div>
    </div>

    <div class="form-group row">
        <div class="col-sm-3 col-form-label"><h5>DLNO20B:</h5></div>
        <div class="col-sm-9"><h5><%= @supplier.dlno20b %></h5></div>
    </div>

    <div class="form-group row">
        <div class="col-sm-3 col-form-label"><h5>DLNO21B:</h5></div>
        <div class="col-sm-9"><h5><%= @supplier.dlno21b %></h5></div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <%= link_to 'Edit', edit_supplier_path(@supplier), class: 'btn btn-warning btn-block' %>
        </div>
        <div class="col-md-6">
            <%= link_to 'Back', suppliers_path, class: 'btn btn-danger btn-block' %>
        </div>
    </div>

   </div>
 </div>
</div>